### PR TITLE
add key support resolves #96

### LINKED ISSUE #96: SpeedDial could not be set key

### PR DESCRIPTION
**Pull request by prateekmedia**

### CODE REVIEW

**Comment by prateekmedia** [comment]
@monouni002 could you test it out please..?

```
flutter_speed_dial:
  git:
    url: git://github.com/darioielardi/flutter_speed_dial
    ref: prateekmedia-key
```

**Comment by monouni002** [comment]
thank you, but i don't see any key in flutter_speed_dial ^^

flutter_speed_dial:
  git:
    url: git://github.com/darioielardi/flutter_speed_dial
    ref: prateekmedia-key

**Comment by monouni002** [comment]
Thank you, but please add that **SpeedDialChild** for me too.

**Comment by prateekmedia** [comment]
@monouni002 Can you test it out? I have also added it for SpeedDialChild but have not tested it..

**Comment by monouni002** [comment]
ok :) can use it, thank you..

**Pull request merged**
