### PR TITLE
provide childAnimation as param

### PR DESCRIPTION
**Pull request by AbhishekDoshi26**
This PR solves issue #246 and allows us to pass `childAnimation` as a separate param.

### CODE REVIEW

**Review by prateekmedia — APPROVED** [review]
LGTM!

**Comment by prateekmedia** [comment]
Can you rebase it, it has conflicts.

**Comment by AbhishekDoshi26** [comment]
Sure. would do that

**Comment by AbhishekDoshi26** [comment]
@prateekmedia done

**Comment by prateekmedia** [comment]
@AbhishekDoshi26 I am quite busy these days and the new maintainer is @luca-colazzo, but he also seems inactive now. If possible please test it yourself and verify that it is working.

**Comment by AbhishekDoshi26** [comment]
Yep. Tested. Working properly.
So, LGTM!
@prateekmedia

**Comment by luca-colazzo** [comment]
Will test when home

**Pull request merged**
