### PR TITLE
support onLongPress for SpeedDialChilds

### PR DESCRIPTION
**Pull request by m0veax**
solves #80 

@jinfagang could you test the feature please?

### CODE REVIEW

**Comment by prateekmedia** [comment]
Seems good. But was he talking about speed dial or speed dial children, that should support this feature?

**Comment by m0veax** [comment]
I understood speed dial child's, but I can add it to the main button too. So we can support both.

**Review by prateekmedia — CHANGES_REQUESTED** [review]
That print statements seems like for debugging only can you remove it so that I can squash and merge it.

As this pr only addresses the speed dial children part, waiting for the speed dial onLongPress if you can do it?

**Review by prateekmedia — APPROVED** [review]

**Comment by m0veax** [comment]
Hey :)

Thanks for merging this. I tried to add longPress support to this package, but since there is a parameter to handle a onPress function, onLongPress becomes the fallback for onPress.

https://github.com/darioielardi/flutter_speed_dial/blob/master/lib/src/speed_dial.dart#L316

I would prefer to not change this, since i see no way to add this feature without breaking backword compatibility. It can be done, but it feeled quirky and i decided i don't want to add ambigious code to this library.

**Comment by prateekmedia** [comment]
@m0veax Nice Decision.

**Pull request merged**
