### PR TITLE
Null safety 🔥🔥

### PR DESCRIPTION
**Pull request by michalisioak**
the example app worked, but I did not have anything else to try it on. #102

### CODE REVIEW

**Comment by prateekmedia** [comment]
@m0veax what do you think? any review

**Comment by m0veax** [comment]
I'm not sure yet. Looks good at all, but does any property needs to be null
safe?

I want to check this, but i have to read more about null safety for this.
Null safety in dart is pretty new for me.

My opinion is, we can merge it now and will not have any breaking changes.

I didn't saw anything that should break.

In my opinion we should merge it in a feature branch, since old dart
versions does not support null safety.

Does anyone knows how pubspec handles this now?

Prateek SU <notifications@github.com> schrieb am Di., 2. März 2021, 16:31:

**Comment by dayron9110** [comment]
This pr should be accepted.
After updating the plugin to the latest version, it did not work in my application, 
but after using this branch, the plugin worked normally.

Thanks @michalisioak for your work.

**Comment by m0veax** [comment]
I agree, but we need to follow this guide for publishing:

https://dart.dev/null-safety/migration-guide#step5-publish

Dayron <notifications@github.com> schrieb am Di., 2. März 2021, 18:12:

**Comment by michalisioak** [comment]
> but does any property needs to be null
safe?

you must either provide a value in the constructor or mark it as required (if it is non final , you can mark it as late)
the ? means that it can be null
[this](https://youtu.be/iYhOU9AuaFs) video helped me to learn the basics of null safety

> Does anyone knows how pubspec handles this now?

I have not published any package but I found [this](https://dart.dev/tools/pub/publishing#publishing-previews)

> In my opinion we should merge it in a feature branch

most of the packages I have seen, they do it this way or the reverse (master is null safety and have another branch for non-null safety)

hope this helps

**Comment by m0veax** [comment]
> > but does any property needs to be null
> safe?
> 
> you must either provide a value in the constructor or mark it as required (if it is non final , you can mark it as late)
> the ? means that it can be null
> [this](https://youtu.be/iYhOU9AuaFs) video helped me to learn the basics of null safety

Thanks for clarifying, I'll have a look later.

> 
> > Does anyone knows how pubspec handles this now?
> 
> I have not published any package but I found [this](https://dart.dev/tools/pub/publishing#publishing-previews)

Maybe a preview release combined with my link before would be the right way, since null safety is a feature in the dart beta release.

> 
> > In my opinion we should merge it in a feature branch
> 
> most of the packages I have seen, they do it this way or the reverse (master is null safety and have another branch for non-null safety)

I would prefer a null safety branch until it reaches a stable release. At this point we should create a backup branch for old flutter versions and merge the null safety features into the master.

@prateekmedia how do you think about this?

**Comment by prateekmedia** [comment]
> I would prefer a null safety branch until it reaches a stable release. At this point we should create a backup branch for old flutter versions and merge the null safety features into the master.
> 
> @prateekmedia how do you think about this?

As I can understand you mean to create a null safety branch seperately and keeping the master branch for stable use, am i right?

**Comment by m0veax** [comment]
@prateekmedia yes, that's right

**Review by prateekmedia — APPROVED** [review]

**Comment by prateekmedia** [comment]
LGTM, thanks!

**Pull request merged**
