### PR TITLE
Possible fix for #117

### PR DESCRIPTION
**Pull request by lks-nbg**
Please review and edit if necessary

### CODE REVIEW

**Comment by lks-nbg** [comment]
Possible fix for #117

**Comment by prateekmedia** [comment]
> Possible fix for #117

Is it for null safe version or is it for no-nullsafety version or for both, as I can see many null checks(`? marks`) there.

**Comment by lks-nbg** [comment]
Since I haven't started migrating my code, I do not have any practical experience with nullsafety yet. But since openCloseDial is declared nullable in the nullsafety branch the code should work there too.

**Comment by kw2019ltd** [comment]
So you can't use flutter stable version 2?

**Comment by lks-nbg** [comment]
@kw2019ltd: I think my post was misleading. I was referring to my personal project, in which I use flutter_speed_dial. I already upgraded it to flutter 2.0, but I have not started the migration to sound-nullsafety, since not all of my dependencies are available yet. So the code of my pull request was tested in flutter 2.0 (without sound-nullsafety) but should also work with sound-nullsafety enabled.

**Comment by prateekmedia** [comment]
LGTM, thanks!

**Pull request merged**
