### PR TITLE
Re-added feature for gradient Color Support

### PR DESCRIPTION
**Pull request by m0veax**
This is solving the merge conflicts in PR #51 

I needed to add a property for the gradients shape, since it does not use the same class as the SpeedDial shape does.

I would be glad if anyone can review and test it, since I don't know all new features that got added recently.

### CODE REVIEW

**Review by prateekmedia — APPROVED** [review]

**Review by prateekmedia — COMMENTED** [review]
Please change these 56 to buttonSize or widget.buttonSize property as it is the new value.

**Comment by m0veax** [comment]
Thanks for your review, i changed the value 56 with the right property now :)

**Comment by m0veax** [comment]
Could you test, if it behave right with a gradient = null and a gradientBoxShape = null?

I'm not sure on this

**Comment by prateekmedia** [comment]
> Could you test, if it behave right with a gradient = null and a gradientBoxShape = null?

Will test when free.

**Pull request merged**
